services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1



  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: secret
    depends_on:
      - zookeeper
      - broker
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  

  producer:
    build: ./producer
    container_name: kafka-producer
    depends_on:
      - zookeeper
      - broker
    volumes:
      - ./dataset:/app/dataset
      - ./logs:/app/logs



  consumer:
    build: ./consumer
    container_name: kafka-consumer
    depends_on:
      - zookeeper
      - broker
      - postgres
    volumes:
      - ./logs:/app/logs


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - zookeeper
      - broker